INSERT IGNORE INTO roles(name) VALUES('ROLE_USER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_VENDOR');
INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');


INSERT  INTO roles(name) VALUES('ROLE_USER');
INSERT  INTO roles(name) VALUES('ROLE_VENDOR');
INSERT  INTO roles(name) VALUES('ROLE_ADMIN');